version: "3.1"
services:
    discordbot:
        image: discordbot
        container_name: discobot
        restart: unless-stopped
    mariadb:
        image: mariadb:latest
        container_name: discobot_db
        restart: unless-stopped
        volumes:
            - ./mariadb/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_DATABASE: discordbot
            MYSQL_USER: discordBot
            MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
        secrets:
            - db_root_password
            - db_user_password
secrets:
    db_root_password:
        file: ./mariadb/secrets/db_root_password.txt
    db_user_password:
        file: ./mariadb/secrets/db_user_password.txt